/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade04.view;

/**
 *
 * @author jotin
 */
public class GenioView extends javax.swing.JFrame {

    
    private int numeroDeAcertos = 0;

    /**
     * Creates new form GenioView
     */
    public GenioView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImageAkineitor = new javax.swing.JLabel();
        lblMensagemPrincipal = new javax.swing.JLabel();
        lblBalaodeTexto = new javax.swing.JLabel();
        spnValorUsuario = new javax.swing.JSpinner();
        btnPalpite = new javax.swing.JButton();
        lblValor = new javax.swing.JLabel();
        lblEnunciado = new javax.swing.JLabel();
        lblAcertos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImageAkineitor.setIcon(new javax.swing.ImageIcon("C:\\Users\\jotin\\OneDrive\\Documentos\\NetBeansProjects\\prg03joaoalvesgomes\\src\\main\\java\\br\\com\\ifba\\atividade04\\imagens\\Akineitor.png")); // NOI18N
        getContentPane().add(lblImageAkineitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 200, 210));

        lblMensagemPrincipal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMensagemPrincipal.setForeground(new java.awt.Color(51, 51, 51));
        lblMensagemPrincipal.setText("<html>VOU PENSAR EM UM VALOR DE 1 EM 5!! <br>TENTE ADIVINHAR<html>");
        getContentPane().add(lblMensagemPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 200, 140));

        lblBalaodeTexto.setIcon(new javax.swing.ImageIcon("C:\\Users\\jotin\\OneDrive\\Documentos\\NetBeansProjects\\prg03joaoalvesgomes\\src\\main\\java\\br\\com\\ifba\\atividade04\\imagens\\Dialogo .png")); // NOI18N
        getContentPane().add(lblBalaodeTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 340, 190));

        spnValorUsuario.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(spnValorUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 130, 30));

        btnPalpite.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        btnPalpite.setText("PALPITE");
        btnPalpite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPalpiteActionPerformed(evt);
            }
        });
        getContentPane().add(btnPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 110, 40));

        lblValor.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lblValor.setText("Valor :");
        getContentPane().add(lblValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 40, -1));

        lblEnunciado.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblEnunciado.setText("Acerte o Número Mágico");
        getContentPane().add(lblEnunciado, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 370, 40));

        lblAcertos.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblAcertos.setText("Acertos = 0");
        getContentPane().add(lblAcertos, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 150, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPalpiteActionPerformed
        // TODO add your handling code here:
        
        int numero = (int)(Math.random() *5) + 1; //gera um numero aleatorio de 1 a 5
        int palpite = (Integer) spnValorUsuario.getValue(); //coleta o palpite do usuario
        if(palpite == numero){ //se palpite igual a numero aleatorio igual a vencedor
            lblMensagemPrincipal.setText("<html>Parabéns,<br>você é um gênio dos números! 🎉<html>");
           numeroDeAcertos++; //adciona 1 no numero de acertos
           lblAcertos.setText("Acertos: "+numeroDeAcertos);
        }else{
            lblMensagemPrincipal.setText("<html>Você errou !!<br>O número era<b> " + numero + " <b><br>Tente outra vez!<html>");
        }
        
    }//GEN-LAST:event_btnPalpiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenioView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPalpite;
    private javax.swing.JLabel lblAcertos;
    private javax.swing.JLabel lblBalaodeTexto;
    private javax.swing.JLabel lblEnunciado;
    private javax.swing.JLabel lblImageAkineitor;
    private javax.swing.JLabel lblMensagemPrincipal;
    private javax.swing.JLabel lblValor;
    private javax.swing.JSpinner spnValorUsuario;
    // End of variables declaration//GEN-END:variables
}
