/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade07.view;

/**
 *
 * @author jotin
 */
public class VetorialView extends javax.swing.JFrame {

    /**
     * Creates new form VetorialView
     */
    public VetorialView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblValor = new javax.swing.JLabel();
        spnValor = new javax.swing.JSpinner();
        bntCalcular = new javax.swing.JButton();
        lblFormula = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblValor.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lblValor.setText("Valor");
        getContentPane().add(lblValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 34, -1));
        getContentPane().add(spnValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 90, 30));

        bntCalcular.setText("Calcular");
        bntCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(bntCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        lblFormula.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lblFormula.setText("Formula");
        getContentPane().add(lblFormula, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        lblResultado.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lblResultado.setText("Resultado");
        getContentPane().add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCalcularActionPerformed
        // TODO add your handling code here:
        try {
        int numero = (Integer) spnValor.getValue(); // obtém o valor do JSpinner
        
        if (numero < 0) {
            lblResultado.setText("Digite um número positivo!");
            lblFormula.setText(""); // Limpa a fórmula se houver erro
            return;
        }
        
        long fatorial = 1;
        StringBuilder formula = new StringBuilder();
        
        // Calcula o fatorial e constrói a fórmula passo a passo
        for (int i = numero; i >= 1; i--) {
            fatorial *= i;
            formula.append(i);
            if (i > 1) {
                formula.append(" x ");
            }
        }
        
        // Exibe a fórmula no lblFormula
        lblFormula.setText(formula.toString());
        
        // Exibe o resultado no lblResultado
        lblResultado.setText("= " + fatorial);
        
    } catch (Exception e) {
        lblFormula.setText(""); // Limpa em caso de erro
        lblResultado.setText("Digite um número válido!");
    }
    }//GEN-LAST:event_bntCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VetorialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VetorialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VetorialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VetorialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VetorialView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCalcular;
    private javax.swing.JLabel lblFormula;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblValor;
    private javax.swing.JSpinner spnValor;
    // End of variables declaration//GEN-END:variables
}
