/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade06.view;
import javax.swing.DefaultListModel;
import java.util.Arrays;  



/**
 *
 * @author jotin
 */
public class VetorView extends javax.swing.JFrame {

    /**
     * Creates new form VetorView
     */
    public VetorView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spnValor = new javax.swing.JSpinner();
        btnAdicionar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnOrdenar = new javax.swing.JButton();
        lblVetor = new javax.swing.JLabel();
        lblvalor = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstLista = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(spnValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 120, 40));

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        btnOrdenar.setText("Ordenar");
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });
        getContentPane().add(btnOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, -1));

        lblVetor.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lblVetor.setText("vetor");
        getContentPane().add(lblVetor, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 60, 20));

        lblvalor.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lblvalor.setText("[0]");
        getContentPane().add(lblvalor, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, -1, -1));

        lstLista.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lstLista.setModel(new javax.swing.DefaultListModel());
        lstLista.setToolTipText("");
        jScrollPane2.setViewportView(lstLista);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 180, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        // TODO add your handling code here:
          int selecionado = lstLista.getSelectedIndex();
          
          if(selecionado != -1){ //V erifica se foi selecionado
          DefaultListModel<String> modelo = (DefaultListModel<String>) lstLista.getModel();
          modelo.set(selecionado, "[" + selecionado + "] -> 0"); // Reseta o valor pra 0 ;)
          }else{
         javax.swing.JOptionPane.showMessageDialog(this, "Selecione um item da lista primeiro!");
          }  
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
        // TODO add your handling code here:
         DefaultListModel<String> modelo = (DefaultListModel<String>) lstLista.getModel();
         
         int[] numeros = new int[modelo.getSize()];
    for (int i = 0; i < modelo.getSize(); i++) {
        String item = modelo.getElementAt(i);
        numeros[i] = Integer.parseInt(item.split("->")[1].trim()); // Pega só o número
    }
      Arrays.sort(numeros);
      
       modelo.clear(); // Limpa a lista
    for (int i = 0; i < numeros.length; i++) {
        modelo.addElement("[" + i + "] -> " + numeros[i]); // Adiciona ordenado
    }
    }//GEN-LAST:event_btnOrdenarActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
            int selecionado = lstLista.getSelectedIndex();//coleta o indice selecionado
            
            if(selecionado !=-1){ //verifica se um numero foi selecionado
            int novoValor = (int) spnValor.getValue(); //pega o valor do spiner
             DefaultListModel<String> modelo = (DefaultListModel<String>) lstLista.getModel(); //atualiza o iten
              modelo.set(selecionado, "[" + selecionado + "] -> " + novoValor); 
            
             } else {// se nada for selecionado
        javax.swing.JOptionPane.showMessageDialog(this, "Selecione um item da lista primeiro!");
    }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        int[] numeros ={0,0,0,0,0,0,0,0,0,0};//cria o array
        DefaultListModel<String> modelo = new DefaultListModel<>();//cria o modelo de lista
        
        
for (int i = 0; i < numeros.length; i++) {
    modelo.addElement("[" + i + "] -> " + numeros[i]);
}
lstLista.setModel(modelo); //passa pra lista
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VetorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VetorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VetorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VetorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VetorView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblVetor;
    private javax.swing.JLabel lblvalor;
    private javax.swing.JList<String> lstLista;
    private javax.swing.JSpinner spnValor;
    // End of variables declaration//GEN-END:variables
}
