/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade03.view;

/**
 *
 * @author jotin
 */
public class CalculadoraView extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraView
     */
    public CalculadoraView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNascimento = new javax.swing.JLabel();
        spnData = new javax.swing.JSpinner();
        BtnCalcular = new javax.swing.JButton();
        lblIdade = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        lblImagenIdade = new javax.swing.JLabel();
        lblPessoas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNascimento.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblNascimento.setText("Ano De Nascimento:");
        getContentPane().add(lblNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 250, 40));

        spnData.setModel(new javax.swing.SpinnerNumberModel(2000, 1900, 2024, 1));
        getContentPane().add(spnData, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 220, 30));

        BtnCalcular.setIcon(new javax.swing.ImageIcon("C:\\Users\\jotin\\OneDrive\\Documentos\\NetBeansProjects\\prg03joaoalvesgomes\\src\\main\\java\\br\\com\\ifba\\atividade03\\images\\icons8-calculadora-de-maçã-50.png")); // NOI18N
        BtnCalcular.setText("Calcular");
        BtnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 130, 60));

        lblIdade.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblIdade.setText("Idade:");
        getContentPane().add(lblIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 80, 30));

        lblResultado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblResultado.setText("0");
        getContentPane().add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 170, 120));

        lblImagenIdade.setIcon(new javax.swing.ImageIcon("C:\\Users\\jotin\\OneDrive\\Documentos\\NetBeansProjects\\prg03joaoalvesgomes\\src\\main\\java\\br\\com\\ifba\\atividade03\\images\\icons8-idade-50.png")); // NOI18N
        getContentPane().add(lblImagenIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 70, 50));

        lblPessoas.setIcon(new javax.swing.ImageIcon("C:\\Users\\jotin\\OneDrive\\Documentos\\NetBeansProjects\\prg03joaoalvesgomes\\src\\main\\java\\br\\com\\ifba\\atividade03\\images\\pessoas (1).png")); // NOI18N
        getContentPane().add(lblPessoas, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 130, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCalcularActionPerformed
       int anoNascimento = (Integer) spnData.getValue();
       int anoAtual = java.util.Calendar.getInstance().get(java.util.Calendar.YEAR);
       int idade = anoAtual - anoNascimento;
       lblResultado.setText(String.valueOf(idade));
     
    }//GEN-LAST:event_BtnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCalcular;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblImagenIdade;
    private javax.swing.JLabel lblNascimento;
    private javax.swing.JLabel lblPessoas;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JSpinner spnData;
    // End of variables declaration//GEN-END:variables
}
