/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade05.view;
import javax.swing.JOptionPane;

/**
 *
 * @author jotin
 */
public class ContadorView extends javax.swing.JFrame {

    /**
     * Creates new form ContadorView
     */
    public ContadorView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        slrInicio = new javax.swing.JSlider();
        slrFim = new javax.swing.JSlider();
        slrPasso = new javax.swing.JSlider();
        lblInico = new javax.swing.JLabel();
        lblFim = new javax.swing.JLabel();
        lblPasso = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblValorInicio = new javax.swing.JLabel();
        lblValorPasso = new javax.swing.JLabel();
        lblValorFim = new javax.swing.JLabel();
        btnContar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResultado.setEditable(false);
        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 190, 300));

        slrInicio.setMaximum(10);
        slrInicio.setMinimum(1);
        slrInicio.setToolTipText("");
        slrInicio.setValue(1);
        slrInicio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slrInicioStateChanged(evt);
            }
        });
        getContentPane().add(slrInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, 20));

        slrFim.setMaximum(20);
        slrFim.setMinimum(1);
        slrFim.setValue(1);
        slrFim.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slrFimStateChanged(evt);
            }
        });
        getContentPane().add(slrFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, 20));

        slrPasso.setMaximum(5);
        slrPasso.setMinimum(1);
        slrPasso.setValue(1);
        slrPasso.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slrPassoStateChanged(evt);
            }
        });
        getContentPane().add(slrPasso, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        lblInico.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblInico.setText("Inicio:");
        getContentPane().add(lblInico, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        lblFim.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblFim.setText("Fim:");
        getContentPane().add(lblFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        lblPasso.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblPasso.setText("Passo:");
        getContentPane().add(lblPasso, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setLabelFor(lblInico);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, -1, -1));

        lblValorInicio.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblValorInicio.setText("0");
        getContentPane().add(lblValorInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 50, 20));

        lblValorPasso.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblValorPasso.setLabelFor(slrPasso);
        lblValorPasso.setText("0");
        getContentPane().add(lblValorPasso, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));

        lblValorFim.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblValorFim.setText("0");
        getContentPane().add(lblValorFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 50, 20));

        btnContar.setText("Contar");
        btnContar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContarActionPerformed(evt);
            }
        });
        getContentPane().add(btnContar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 80, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void slrInicioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slrInicioStateChanged
        // TODO add your handling code here:
         lblValorInicio.setText(String.valueOf(slrInicio.getValue())); //atualiza o valor do lblValorInico com o valor do slider
    }//GEN-LAST:event_slrInicioStateChanged

    private void slrFimStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slrFimStateChanged
 lblValorFim.setText(String.valueOf(slrFim.getValue()));//atualiza o valor do lblValorFim com o valor do slider
    }//GEN-LAST:event_slrFimStateChanged

    private void slrPassoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slrPassoStateChanged
        // TODO add your handling code here:
        lblValorPasso.setText(String.valueOf(slrPasso.getValue()));//atualiza o valor do lblValorPasso com o valor do slider
    }//GEN-LAST:event_slrPassoStateChanged

    private void btnContarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContarActionPerformed
        // TODO add your handling code here:
         int inicio = Integer.parseInt(lblValorInicio.getText());
        int fim = Integer.parseInt(lblValorFim.getText());
        int passo = Integer.parseInt(lblValorPasso.getText()); // cria as variaveis e coleta os valores
    
    if (passo == 0) {
        JOptionPane.showMessageDialog(this, "O passo não pode ser zero!");
        return; //verifica se o Passo é 0
    }

    
    StringBuilder sequencia = new StringBuilder();
    for (int i = inicio; i <= fim; i += passo) { // gera a sequencia
        sequencia.append(i).append("\n"); // Adiciona cada número + quebra de linha
    }
    
    // 4. Exibi o resultado
    txtResultado.setText(sequencia.toString());
    
    
    
    
    
    
    
    }//GEN-LAST:event_btnContarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContadorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContadorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContadorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContadorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContadorView().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFim;
    private javax.swing.JLabel lblInico;
    private javax.swing.JLabel lblPasso;
    private javax.swing.JLabel lblValorFim;
    private javax.swing.JLabel lblValorInicio;
    private javax.swing.JLabel lblValorPasso;
    private javax.swing.JSlider slrFim;
    private javax.swing.JSlider slrInicio;
    private javax.swing.JSlider slrPasso;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
