/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade09.view;
import br.com.ifba.atividade09.intefaces.InterfacePagamento;
import br.com.ifba.atividade09.Implementacoes.PagamentoCartao;
import br.com.ifba.atividade09.Implementacoes.PagamentoDinheiro;
import br.com.ifba.atividade09.Implementacoes.PagamentoPix;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;


/**
 *
 * @author jotin
 */
public class SistemeView extends javax.swing.JFrame {

    /**
     * Creates new form SistemeView
     */
    public SistemeView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtdigitarNome = new javax.swing.JTextField();
        lbldigitarNome = new javax.swing.JLabel();
        cmbTipoPagamento = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtdigitarValor = new javax.swing.JTextField();
        btnpagar = new javax.swing.JToggleButton();
        lblSelecione = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtdigitarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdigitarNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtdigitarNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 90, -1));

        lbldigitarNome.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lbldigitarNome.setText("Digite seu nome:");
        getContentPane().add(lbldigitarNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        cmbTipoPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pagamento Cartão", "Pagamento Dinheiro", "Pagamento Pix" }));
        cmbTipoPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoPagamentoActionPerformed(evt);
            }
        });
        getContentPane().add(cmbTipoPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 170, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel1.setText("Valor da Compra:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 120, -1));

        txtdigitarValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdigitarValorActionPerformed(evt);
            }
        });
        getContentPane().add(txtdigitarValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 90, -1));

        btnpagar.setText("Pagar");
        btnpagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpagarActionPerformed(evt);
            }
        });
        getContentPane().add(btnpagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        lblSelecione.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lblSelecione.setText("Selecione a forma de pagamento");
        getContentPane().add(lblSelecione, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\jotin\\OneDrive\\Documentos\\NetBeansProjects\\prg03joaoalvesgomes\\src\\main\\java\\br\\com\\ifba\\atividade09\\view\\imagens\\Fundo.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-230, -190, 630, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdigitarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdigitarNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdigitarNomeActionPerformed

    private void txtdigitarValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdigitarValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdigitarValorActionPerformed

    private void btnpagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpagarActionPerformed
  // Obtém o tipo de pagamento selecionado no comboBox
String tipoPagamento = (String) cmbTipoPagamento.getSelectedItem();

// Pega o nome digitado pelo usuário
String nome = txtdigitarNome.getText();

// Gera a data atual formatada como "dia/mês/ano"
String data = LocalDate.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));

double valorCompra;

try {
    // Tenta converter o texto digitado para um número (double)
    valorCompra = Double.parseDouble(txtdigitarValor.getText());
} catch (NumberFormatException e) {
    // Se o valor digitado não for numérico, mostra uma mensagem de erro
    JOptionPane.showMessageDialog(null, "Digite um valor válido.", "Erro", JOptionPane.ERROR_MESSAGE);
    return;
}

// Validação: o valor da compra não pode ser negativo
if (valorCompra < 0) {
    JOptionPane.showMessageDialog(null, "Valor não pode ser menor que 0,00 R$", "ERROR", JOptionPane.ERROR_MESSAGE);
    return;
}

InterfacePagamento pagamento;

// Aqui, decidimos qual tipo de pagamento será usado, de acordo com a escolha do usuário
switch (tipoPagamento) {
    case "Pagamento Cartão":
        pagamento = new PagamentoCartao(); // Cria objeto para pagamento com cartão
        break;
    case "Pagamento Dinheiro":
        pagamento = new PagamentoDinheiro(); // Cria objeto para pagamento em dinheiro
        break;
    case "Pagamento Pix":
        pagamento = new PagamentoPix(); // Cria objeto para pagamento via Pix
        break;
    default:
        // Se o tipo de pagamento não for reconhecido, mostra erro e para a execução
        JOptionPane.showMessageDialog(null, "Tipo de pagamento inválido.");
        return;
}

// Calcula o valor final da compra com base nas regras do tipo de pagamento escolhido
double valorFinal = pagamento.calcularTotal(valorCompra);

// Por fim, imprime um recibo com os dados da compra
pagamento.imprimirRecibo(nome, data, valorCompra, valorFinal);

       
    }//GEN-LAST:event_btnpagarActionPerformed

    private void cmbTipoPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoPagamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnpagar;
    private javax.swing.JComboBox<String> cmbTipoPagamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblSelecione;
    private javax.swing.JLabel lbldigitarNome;
    private javax.swing.JTextField txtdigitarNome;
    private javax.swing.JTextField txtdigitarValor;
    // End of variables declaration//GEN-END:variables
}
